#if !canImport(ObjectiveC)
import XCTest

extension BorderTest {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__BorderTest = [
    ("testSingleEmpty", testSingleEmpty),
  ]
}

extension CellQueriesTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__CellQueriesTests = [
    ("testDates", testDates),
  ]
}

extension CellReferenceTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__CellReferenceTests = [
    ("testCellReference", testCellReference),
    ("testColumnReference", testColumnReference),
    ("testColumnReferenceAdvancedBy", testColumnReferenceAdvancedBy),
    ("testColumnReferenceComparable", testColumnReferenceComparable),
    ("testColumnReferenceDistance", testColumnReferenceDistance),
    ("testColumnReferenceIntInitializer", testColumnReferenceIntInitializer),
    ("testColumnReferenceIntInitializerPerformance", testColumnReferenceIntInitializerPerformance),
    ("testColumnReferenceStringInitializerPerformance", testColumnReferenceStringInitializerPerformance),
  ]
}

extension CommentsTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__CommentsTests = [
    ("testComments", testComments),
  ]
}

extension CoreXLSXTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__CoreXLSXTests = [
    ("testBlank", testBlank),
    ("testDates", testDates),
    ("testHelloWorld", testHelloWorld),
    ("testLegacyPublicAPI", testLegacyPublicAPI),
    ("testMultiline", testMultiline),
    ("testPublicAPI", testPublicAPI),
    ("testRootRelationships", testRootRelationships),
  ]
}

extension FormulaTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__FormulaTests = [
    ("testFormulas", testFormulas),
  ]
}

extension NamespacesTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__NamespacesTests = [
    ("testNamespaces", testNamespaces),
  ]
}

extension RelationshipsTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__RelationshipsTests = [
    ("testCustomXmlSchemaType", testCustomXmlSchemaType),
    ("testPersonRelationship", testPersonRelationship),
    ("testRelationshipsFaultyWorksheet", testRelationshipsFaultyWorksheet),
    ("testRelationshipsFromFile", testRelationshipsFromFile),
    ("testRelationshipsXML", testRelationshipsXML),
  ]
}

extension SharedStringsTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__SharedStringsTests = [
    ("testRichTextXML", testRichTextXML),
    ("testSharedStrings", testSharedStrings),
    ("testSharedStringsOrder", testSharedStringsOrder),
    ("testSpacePreserve", testSpacePreserve),
  ]
}

extension StylesTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__StylesTests = [
    ("testStyles", testStyles),
  ]
}

extension WorkbookTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__WorkbookTests = [
    ("testWorkbook", testWorkbook),
    ("testWorkbookNoViews", testWorkbookNoViews),
    ("testWorksheetPathsAndNames", testWorksheetPathsAndNames),
  ]
}

extension WorksheetTests {
  // DO NOT MODIFY: This is autogenerated, use:
  //   `swift test --generate-linuxmain`
  // to regenerate.
  static let __allTests__WorksheetTests = [
    ("testExample", testExample),
  ]
}

public func __allTests() -> [XCTestCaseEntry] {
  [
    testCase(BorderTest.__allTests__BorderTest),
    testCase(CellQueriesTests.__allTests__CellQueriesTests),
    testCase(CellReferenceTests.__allTests__CellReferenceTests),
    testCase(CommentsTests.__allTests__CommentsTests),
    testCase(CoreXLSXTests.__allTests__CoreXLSXTests),
    testCase(FormulaTests.__allTests__FormulaTests),
    testCase(NamespacesTests.__allTests__NamespacesTests),
    testCase(RelationshipsTests.__allTests__RelationshipsTests),
    testCase(SharedStringsTests.__allTests__SharedStringsTests),
    testCase(StylesTests.__allTests__StylesTests),
    testCase(WorkbookTests.__allTests__WorkbookTests),
    testCase(WorksheetTests.__allTests__WorksheetTests),
  ]
}
#endif
