name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: MaxDesiatov/swift-doc@patch-2
        with:
          inputs: "Sources"
          module-name: CoreXLSX
          format: html
          output: ./.build/documentation
      - run: sudo chmod o+r -R ./.build/documentation
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build/documentation
