name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  xcode_12_0:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          ./test_xcodebuild.sh Xcode_12
        env:
          IOS_DEVICE: "platform=iOS Simulator,OS=14.0,name=iPhone 8"
          TVOS_DEVICE: "platform=tvOS Simulator,OS=14.0,name=Apple TV 4K"

  xcode_12_1:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          ./test_xcodebuild.sh Xcode_12.1
        env:
          IOS_DEVICE: "platform=iOS Simulator,OS=14.1,name=iPhone 8"
          TVOS_DEVICE: "platform=tvOS Simulator,OS=14.0,name=Apple TV 4K"

  xcode_12_2:
    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: |
          ./test_xcodebuild.sh Xcode_12.2
        env:
          IOS_DEVICE: "platform=iOS Simulator,OS=14.2,name=iPhone 8"
          TVOS_DEVICE: "platform=tvOS Simulator,OS=14.2,name=Apple TV 4K"
