name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos_build:
    strategy:
      matrix:
        include:
          - xcode: "11.7" # Swift 5.2
            macOS: "10.15"
            iOS: "13.7"
            tvOS: "13.4"
            useCodecov: "false"
          - xcode: "12.4" # Swift 5.3
            macOS: "10.15"
            iOS: "14.4"
            tvOS: "14.3"
            useCodecov: "false"
          - xcode: "12.5.1" # Swift 5.4
            macOS: "11.0"
            iOS: "14.5"
            tvOS: "14.5"
            useCodecov: "false"
          - xcode: "13.1" # Swift 5.5
            macOS: "11.0"
            iOS: "15.0"
            tvOS: "15.0"
            useCodecov: "false"
          - xcode: "13.4.1" # Swift 5.6
            macOS: "12"
            iOS: "15.5"
            tvOS: "15.4"
            useCodecov: "true"

    runs-on: macos-${{ matrix.macOS }}
    name: Build with Xcode ${{ matrix.xcode }} on macOS ${{ matrix.macOS }}

    steps:
      - uses: actions/checkout@v2

      - name: Build with Xcode ${{ matrix.xcode }}
        run: ./test_xcodebuild.sh Xcode_${{ matrix.xcode }}
        env:
          IOS_DEVICE: "platform=iOS Simulator,OS=${{ matrix.iOS }},name=iPhone 8"
          TVOS_DEVICE: "platform=tvOS Simulator,OS=${{ matrix.tvOS }},name=Apple TV"
          CODECOV_JOB: ${{ matrix.useCodecov }}
          CODECOV_TOKEN: ${{ secrets.codecovToken }}

  pod-lib-lint:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Run CocoaPods linter
        run: ./pod.sh

  linux_build:
    strategy:
      matrix:
        swift:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"

    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery
